name: Checks
on: [push]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
  forge:
    name: Forge
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Install forge dependencies
        run: forge install
      - name: Run forge tests
        run: forge test --match-path test/foundry/unit/**/*.t.sol
      - name: Inspect storage layouts
        run: ./scripts/checkStorageLayout.sh
  solhint:
    name: Solhint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Solhint
        run: yarn lint-contracts
