name: Checks
"on":
  - push
  - pull_request
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: "Use Node ${{ matrix.node }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node }}"
          cache: yarn
      - name: Setup Anchor & Build
        uses: metadaoproject/setup-anchor@v2
        with:
          anchor-version: 0.30.1
          solana-cli-version: 1.18.21
          node-version: 20.17.0
      - name: Create keypair
        run: solana-keygen new --no-bip39-passphrase
        shell: bash
      - name: Make Anchor.toml compatible with runner
        run: "sed -i 's:/user/:/runner/:' Anchor.toml"
        shell: bash
      - name: Install Cargo toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustc
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Lint
        shell: bash
        run: yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: "Use Node ${{ matrix.node }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node }}"
          cache: yarn
      - name: Setup Anchor & Build
        uses: metadaoproject/setup-anchor@v2
        with:
          anchor-version: 0.30.1
          solana-cli-version: 1.18.21
          node-version: 20.17.0
      - name: Create keypair
        run: solana-keygen new --no-bip39-passphrase
        shell: bash
      - name: Make Anchor.toml compatible with runner
        run: "sed -i 's:/user/:/runner/:' Anchor.toml"
        shell: bash
      - name: Install Cargo toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustc
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Test EVM
        shell: bash
        run: yarn test-evm
      - name: Test SVM
        shell: bash
        run: yarn test-svm
  forge:
    name: Forge
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: "Use Node ${{ matrix.node }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node }}"
          cache: yarn
      - name: Setup Anchor & Build
        uses: metadaoproject/setup-anchor@v2
        with:
          anchor-version: 0.30.1
          solana-cli-version: 1.18.21
          node-version: 20.17.0
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Install forge dependencies
        run: forge install
      - name: Inspect storage layouts
        run: ./scripts/checkStorageLayout.sh
      - name: Run forge test
        run: forge test --match-path test/evm/foundry/local/**/*.t.sol
  solhint:
    name: Solhint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Solhint
        run: yarn lint-contracts
