name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Additional dependencies
        run: |
          apt-get update -y
          apt-get -y install rsync

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v2

      - name: Test
        run: yarn test
